name: Test Workflow

on:
  push:

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Install WASM tools
        run: |
          dotnet workload install wasm-tools
          dotnet workload install wasm-experimental
      - name: Publish
        run: dotnet build --configuration Release
      - name: list
        run: ls -al ./dist
